# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxCocoa_PopUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxCocoa_PopUp
  pod 'SnapKit'
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa'
  pod 'RxRelay'

end
